[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "annoy",
    "fastapi==0.115.6",
    "langchain==0.3.14",
    "langchain-community==0.3.14",
    "langchain-huggingface==0.1.2",
    "langchain-qdrant==0.2.0",
    "langchain-text-splitters==0.3.5",
    "litellm==1.56.10",
    "logfire[fastapi]==2.11.1",
    "nemoguardrails==0.11.1",
    "pydantic==2.10.4",
    "pydantic-settings==2.7.1",
    "python-dotenv==1.0.1",
    "qdrant-client==1.12.1",
    "sentence-transformers==3.3.1",
    "slowapi==0.1.9",
    "uvicorn[standard]==0.34.0",
]

[tool.uv.sources]
annoy = { url = "https://github.com/Sprocketer/annoy-wheels/raw/main/annoy-1.17.3-cp312-cp312-win_amd64.whl", marker = "sys_platform == 'win32'" }
